### ISSUE TITLE
about data set 

### ISSUE THREAD

**Issue by ctoshio** [ZihanWangKi/extend_bert#2]
Your paper is very good, I would like to reproduce the experiment in the paper. However, I cannot find the data set. Excuse me, can you provide the data set needed for the experiment? Thank you!

**Comment by ZihanWangKi** [comment]
Hi,

The datasets are from the LORELEI project (https://www.darpa.mil/program/low-resource-languages-for-emergent-incidents).  I heard that it would be open-sourced in some time, but I have recently lost track of it. 

Best,
Zihan
