### ISSUE TITLE
using this as a base model

### ISSUE THREAD

**Issue by SankhaJay** [ZihanWangKi/extend_bert#3]
Hi, I found your work very interesting and very excited to see that you have used my native language Sinhala also. 

Can you please walk me through that how can I use your e-mbert model as the base model for another task like question-answering in the Sinhala language.

**Comment by ZihanWangKi** [comment]
Hi,

You may download the model for Sinhala [here]( https://cogcomp.seas.upenn.edu/models/bert_pretrained_models_lorelei/EMBERT_sin_step_500k.tgz). Upon extracting, you can use the [transformers](https://github.com/huggingface/transformers) module to load the model.

**Comment by SankhaJay** [comment]
@ZihanWangKi sorry for the late reply and thank you very much for sharing such a valuable resource. Cheers !!
